### PR TITLE
Enhancing the Accessibility of page elements

### PR DESCRIPTION
**Pull request by MuhmmdUsama**
**We @S-imba  checked the site elements' accessibility for ( Mobil and Desktop ) versions**

- Manual check
- Auto check

and everything is ok and my report checkup gives me 96%

Screenshot 2022-03-29 132440

****There are two issues with color contrast****
- buttons
- Labels of ( Skills ) part

but I have no hand in that because I followed the rules of the color pallet of [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=37%3A2337)

Screenshot 2022-03-29 133424

****Portfolio Accessibility Report****
-

- [ ] Page title - No issues found
- [ ] Image text alternatives - No issues found
- [ ] Text headings - No issues found
- [ ] Color contrast - Background and foreground colors do not have a sufficient contrast ratio (buttons & Labels).
- [ ] Resize - No issues found
- [ ] Interaction - No issues found
- [ ] Moving content - No issues found
- [ ] Multimedia - No issues found
- [ ] The basic structure of the page -No issues found

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
> **I checked the site elements' accessibility for ( Mobil and Desktop ) versions**
> 
> * Manual check
> * Auto check
> 
> and everything is ok and my report checkup gives me 96%
> 
> Screenshot 2022-03-29 132440
> 
> ****There are two issues with color contrast****
> 
> * buttons
> * Labels of ( Skills ) part
> 
> but I have no hand in that because I followed the rules of the color pallet of [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=37%3A2337)
> 
> Screenshot 2022-03-29 133424

Hi @MuhmmdUsama well-done checking the site accessibility, 
- [x] Kindly prepare a report listing all points that you have checked, and the result of your evaluation, Check the comment under the review.


 Your report should include:
List all points that you have checked, i.e:
- Page titles
- Image text alternatives** (alt text)
- Text headings
- Color contrast
- Resize
- Interaction
- Moving content
- Multimedia
- The basic structure of the page

#### Each point on the list needs to include the result of your evaluation:
If everything was ok, make a statement about that (e.g. "Page titles - no issues found").



- [x] Kindly add your report   to the description of your pull request, please do this because this is part of the [project requirements 
](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md)

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ GitHub flow was correctly used




## Required Changes ♻️
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MuhmmdUsama** [comment]
I completed all the requirements

**Comment by MuhmmdUsama** [comment]
I completed all the requirements

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @MuhmmdUsama,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
